#
# Vivado (TM) v2016.3 (64-bit)
#
# proj.tcl: Tcl script for re-creating project 'spi_flash'
#
# Generated by Vivado on Mon Nov 05 09:43:59 -0600 2018
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#

#-----------------------------------------------------------
# Constant parameters
#-----------------------------------------------------------
set proj_name spi_flash
set design_ver v1_0
set underscore _
set design_name_full "$proj_name$underscore$design_ver"
puts "NOTE: This file must be executed from the project's 'tcl' directory"

#-----------------------------------------------------------
# Archive existing design if it already exists
#-----------------------------------------------------------
puts "NOTE: Archive existing $design_name_full design if it exists"
set format_date [clock format [clock seconds] -format %Y%m%d_%H%m]
set date_suffix $underscore$format_date
if { [file exists "../proj/$design_name_full"] == 1 } { 
  puts "Moving existing $design_name_full to time-stamped suffix $design_name_full$date_suffix"
  file rename "../proj/$design_name_full" "../proj/$design_name_full$date_suffix"
} else {
  file mkdir ../proj
}

#-----------------------------------------------------------
# Create project
#-----------------------------------------------------------
puts "Creating project $design_name_full..."
create_project $design_name_full "../proj/$design_name_full" -part xc7a200tfbg484-2

#-----------------------------------------------------------
# Create sources_1 fileset (if not found)
#-----------------------------------------------------------
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}
set obj [get_filesets sources_1]

#-----------------------------------------------------------
# Add HDL IP repositories
#-----------------------------------------------------------
set_property ip_repo_paths "../ip" $obj
update_ip_catalog -rebuild

#-----------------------------------------------------------
# Create BD source
#-----------------------------------------------------------
puts "Creating block diagram..."
source "../bds/design_1.tcl"
make_wrapper -files [get_files "design_1.bd"] -top
import_files -force -norecurse "../proj/$design_name_full/$design_name_full.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v"

#-----------------------------------------------------------
# Create 'constrs_1' fileset (if not found)
#-----------------------------------------------------------
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "../xdc/ccd_daq.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]

#-----------------------------------------------------------
# Create 'sim_1' fileset (if not found)
#-----------------------------------------------------------
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "design_1_wrapper" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

#-----------------------------------------------------------
# Create 'synth_1' run (if not found)
#-----------------------------------------------------------
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a200tfbg484-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7a200tfbg484-2" $obj

#-----------------------------------------------------------
# Create 'impl_1' run (if not found)
#-----------------------------------------------------------
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a200tfbg484-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7a200tfbg484-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:spi_flash"
